name: Build and Push pyAFQ CUDA12 Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build pyAFQ GPU docker image
      run: sh ./gpu_docker/docker-build.sh \
        "${{github.sha}}" "nrdg" "12.0.1-devel-ubuntu20.04" "12"

    - name: Build a tagged GPU image
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        sh ./gpu_docker/docker-build.sh \
          "${GITHUB_REF:10}" "nrdg" "12.0.1-devel-ubuntu20.04" "12"

    - name: Login to GHCR 
      if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags')
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: nrdg
        password: ${{secrets.CR_PAT_NRDG}}

    - name: Push pyAFQ GPU docker image
      if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags')
      run: sh ./gpu_docker/docker-push.sh "nrdg" "12"
