name: Build and Push pyAFQ Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build pyAFQ docker image
      run: sh ./pyafq_docker/docker-build.sh \
        "${{github.sha}}" "nrdg"

    - name: Build a tagged image
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        sh ./pyafq_docker/docker-build.sh \
          "${GITHUB_REF:10}" "nrdg"

    - name: Login to GHCR 
      if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags')
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: nrdg
        password: ${{secrets.CR_PAT_NRDG}}

    - name: Push pyAFQ docker image
      if: github.ref == 'refs/heads/master' || startsWith(github.event.ref, 'refs/tags')
      run: sh ./pyafq_docker/docker-push.sh "nrdg"
