name: Build and Push pyAFQ and AFQsi Docker Image

on: [push] # use these while testing
  # push:
  #   branches:
  #     - 'master'
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: nrdg
        password: ${{secrets.CR_PAT_NRDG}}

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Build and push pyAFQ docker image
      run: sh ./pyafq_docker/docker-build.sh \
        "${{github.sha}}" \
        "nrdg"

    - name: Build and push AFQsi docker image
      run: sh ./afqsi_docker/docker-build.sh \
        "${{github.sha}}" \
        "nrdg"
